name: Build

on:
  push:
    branches: [ master ]

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
        make packer
