name: Build

on:
  push:
    branches: [ master ]

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      run: |
        make docker
